### PR TITLE
Map qt6

### LINKED ISSUE #4663: [Bug]: MacOS Qt6 build - maps and statistics problems
### Description

Two problems with the new 6.0.5504 Qt6 build, at least on arm64 MacOS Sequioa. App was downloaded from the Github offical builds: Subsurface-arm64-qt6-6.0.5504-CICD-release.dmg

These problems are consistently reproducible immediately after starting Subsurface, even with an empty divelog loaded. 

1.  the Maps pane is not scrollable. Zooming works, but cannot move the map by dragging with the mouse.
2. Selecting View -> Dive Statistics (cmd-T) causes subsurface to crash with a segfault. Backtrace attached.

Neither of these problems is evident on the Qt5 build of 6.0.5504 arm64 MacOS Sequoia

### Subsurface Version

6.0.5504 arm64 Qt6 official build

### Platform(s)

macOS

### Platform Version

MacOS Sequoia 15.7.3 arm64

### Divecomputer Model

n/a

### Steps to Reproduce

Start subsurface with any divelog loaded, even an empty one.

1. Try to scroll the maps pane by dragging with the mouse - map does not move.
2. Select View -> Dive Statistics. Application crashes with a seg fault.

### Logs

```shell
crash report: 
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11

...

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   QtQuick                       	       0x104d7a00c QSGSoftwareRenderableNode::update() + 536
1   QtQuick                       	       0x104d7c728 0x104c5c000 + 1181480
2   QtQuick                       	       0x104db738c QSGNodeVisitorEx::visitChildren(QSGNode*) + 108
3   QtQuick                       	       0x104d7e0b4 0x104c5c000 + 1188020
4   QtQuick                       	       0x104d6e6d8 QSGAbstractSoftwareRenderer::nodeAdded(QSGNode*) + 140
5   QtQuick                       	       0x104d6e10c QSGAbstractSoftwareRenderer::nodeChanged(QSGNode*, QFlags<QSGNode::DirtyStateBit>) + 164
6   QtQuick                       	       0x104dab17c QSGNode::appendChildNode(QSGNode*) + 144
7   Subsurface                    	       0x1027b2588 StatsView::addQSGNode(QSGNode*, ChartZValue) + 108
8   Subsurface                    	       0x10272e76c ChartPixmapItem::render(StatsTheme const&) + 120
9   Subsurface                    	       0x1027b2374 StatsView::updatePaintNode(QSGNode*, QQuickItem::UpdatePaintNodeData*) + 252
10  QtQuick                       	       0x104d5f95c QQuickWindowPrivate::updateDirtyNode(QQuickItem*) + 2712
11  QtQuick                       	       0x104d59bc0 QQuickWindowPrivate::updateDirtyNodes() + 408
12  QtQuick                       	       0x104d59714 QQuickWindowPrivate::syncSceneGraph() + 452
13  QtQuick                       	       0x104cf5e34 QQuickRenderControl::sync() + 68
14  QtQuickWidgets                	       0x1033be4b0 0x1033b4000 + 42160
15  QtWidgets                     	       0x105d41548 QWidget::event(QEvent*) + 992
16  QtQuickWidgets                	       0x1033c1f98 QQuickWidget::event(QEvent*) + 852
17  QtWidgets                     	       0x105cef96c QApplicationPrivate::notify_helper(QObject*, QEvent*) + 336
18  QtWidgets                     	       0x105cf13ec QApplication::notify(QObject*, QEvent*) + 3260
19  QtCore                        	       0x10637389c QCoreApplication::notifyInternal2(QObject*, QEvent*) + 200
20  QtWidgets                     	       0x105d3d2cc QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) + 1492
21  QtWidgets                     	       0x105d3d520 QWidget::setGeometry(QRect const&) + 200
22  QtWidgets                     	       0x105d21244 QWidgetItem::setGeometry(QRect const&) + 688
23  QtWidgets                     	       0x105cfc114 QBoxLayout::setGeometry(QRect const&) + 964
24  QtWidgets                     	       0x105d1dbe8 QLayoutPrivate::doResize() + 368
25  QtWidgets                     	       0x105d1de80 QLayout::activate() + 448
26  QtWidgets                     	       0x105cef940 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 292
27  QtWidgets                     	       0x105cf13ec QApplication::notify(QObject*, QEvent*) + 3260
28  QtCore                        	       0x10637389c QCoreApplication::notifyInternal2(QObject*, QEvent*) + 200
29  QtWidgets                     	       0x105d3d2cc QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) + 1492
30  QtWidgets                     	       0x105d3d520 QWidget::setGeometry(QRect const&) + 200
31  QtWidgets                     	       0x105ecf768 0x105ce0000 + 2029416
32  QtWidgets                     	       0x105ecf510 0x105ce0000 + 2028816
33  QtWidgets                     	       0x105d41548 QWidget::event(QEvent*) + 992
34  QtWidgets                     	       0x105dc7504 QFrame::event(QEvent*) + 56
35  QtWidgets                     	       0x105cef96c QApplicationPrivate::notify_helper(QObject*, QEvent*) + 336
36  QtWidgets                     	       0x105cf13ec QApplication::notify(QObject*, QEvent*) + 3260
37  QtCore                        	       0x10637389c QCoreApplication::notifyInternal2(QObject*, QEvent*) + 200
38  QtWidgets                     	       0x105d3d2cc QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) + 1492
39  QtWidgets                     	       0x105d3d520 QWidget::setGeometry(QRect const&) + 200
40  QtWidgets                     	       0x105ecf768 0x105ce0000 + 2029416
41  QtWidgets                     	       0x105ecf510 0x105ce0000 + 2028816
42  QtWidgets                     	       0x105ecee70 0x105ce0000 + 2027120
43  QtWidgets                     	       0x105ed1388 QSplitter::event(QEvent*) + 132
44  QtWidgets                     	       0x105cef96c QApplicationPrivate::notify_helper(QObject*, QEvent*) + 336
45  QtWidgets                     	       0x105cf13ec QApplication::notify(QObject*, QEvent*) + 3260
46  QtCore                        	       0x10637389c QCoreApplication::notifyInternal2(QObject*, QEvent*) + 200
47  QtCore                        	       0x1063749a8 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 532
48  libqcocoa.dylib               	       0x1056f8fa4 0x1056e0000 + 102308
49  libqcocoa.dylib               	       0x1056fa1f0 0x1056e0000 + 106992
50  CoreFoundation                	       0x18caaea64 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
51  CoreFoundation                	       0x18caae9f8 __CFRunLoopDoSource0 + 172
52  CoreFoundation                	       0x18caae764 __CFRunLoopDoSources0 + 232
53  CoreFoundation                	       0x18caad3b8 __CFRunLoopRun + 840
54  CoreFoundation                	       0x18caac9e8 CFRunLoopRunSpecific + 572
55  HIToolbox                     	       0x19854d27c RunCurrentEventLoopInMode + 324
56  HIToolbox                     	       0x1985504e8 ReceiveNextEventCommon + 676
57  HIToolbox                     	       0x1986db484 _BlockUntilNextEventMatchingListInModeWithFilter + 76
58  AppKit                        	       0x1909cda34 _DPSNextEvent + 684
59  AppKit                        	       0x19136c940 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
60  AppKit                        	       0x1909c0be4 -[NSApplication run] + 480
61  libqcocoa.dylib               	       0x1056f7adc 0x1056e0000 + 96988
62  QtCore                        	       0x10637d884 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 596
63  QtCore                        	       0x106374078 QCoreApplication::exec() + 144
64  Subsurface                    	       0x1021dbee0 run_ui() + 24
65  Subsurface                    	       0x1021d5b28 main + 2184
66  dyld                          	       0x18c622b98 start + 6076

Thread 1:
0   libsystem_pthread.dylib       	       0x18c9beb6c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18c9beb6c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x18c9beb6c start_wqthread + 0

Thread 4:: QNetworkAccessManager thread
0   libsystem_kernel.dylib        	       0x18c98a498 poll + 8
1   QtCore                        	       0x1064f8d60 qt_safe_poll(pollfd*, unsigned int, QDeadlineTimer) + 168
2   QtCore                        	       0x1064fc9c4 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 904
3   QtCore                        	       0x10637d884 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 596
4   QtCore                        	       0x106465594 QThread::exec() + 332
5   QtCore                        	       0x1064fa7b4 0x1062e0000 + 2205620
6   libsystem_pthread.dylib       	       0x18c9c3bc8 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x18c9beb80 thread_start + 8

Thread 5:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18c9853cc __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18c9c409c _pthread_cond_wait + 984
2   QtCore                        	       0x106508c28 0x1062e0000 + 2264104
3   QtCore                        	       0x106508aa0 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x106502a64 0x1062e0000 + 2239076
5   QtCore                        	       0x1064fa7b4 0x1062e0000 + 2205620
6   libsystem_pthread.dylib       	       0x18c9c3bc8 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x18c9beb80 thread_start + 8

Thread 6:
0   libsystem_pthread.dylib       	       0x18c9beb6c start_wqthread + 0

Thread 7:: QQmlThread
0   libsystem_kernel.dylib        	       0x18c98a498 poll + 8
1   QtCore                        	       0x1064f8d04 qt_safe_poll(pollfd*, unsigned int, QDeadlineTimer) + 76
2   QtCore                        	       0x1064fc9c4 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 904
3   QtCore                        	       0x10637d884 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 596
4   QtCore                        	       0x106465594 QThread::exec() + 332
5   QtCore                        	       0x1064fa7b4 0x1062e0000 + 2205620
6   libsystem_pthread.dylib       	       0x18c9c3bc8 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x18c9beb80 thread_start + 8

Thread 8:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18c9853cc __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18c9c409c _pthread_cond_wait + 984
2   QtCore                        	       0x106508c28 0x1062e0000 + 2264104
3   QtCore                        	       0x106508aa0 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x106502a64 0x1062e0000 + 2239076
5   QtCore                        	       0x1064fa7b4 0x1062e0000 + 2205620
6   libsystem_pthread.dylib       	       0x18c9c3bc8 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x18c9beb80 thread_start + 8

Thread 9:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18c9853cc __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18c9c409c _pthread_cond_wait + 984
2   QtCore                        	       0x106508c28 0x1062e0000 + 2264104
3   QtCore                        	       0x106508aa0 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x106502a64 0x1062e0000 + 2239076
5   QtCore                        	       0x1064fa7b4 0x1062e0000 + 2205620
6   libsystem_pthread.dylib       	       0x18c9c3bc8 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x18c9beb80 thread_start + 8

Thread 10:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18c9853cc __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18c9c409c _pthread_cond_wait + 984
2   QtCore                        	       0x106508c28 0x1062e0000 + 2264104
3   QtCore                        	       0x106508aa0 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x106502a64 0x1062e0000 + 2239076
5   QtCore                        	       0x1064fa7b4 0x1062e0000 + 2205620
6   libsystem_pthread.dylib       	       0x18c9c3bc8 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x18c9beb80 thread_start + 8

Thread 11:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18c9853cc __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18c9c409c _pthread_cond_wait + 984
2   QtCore                        	       0x106508c28 0x1062e0000 + 2264104
3   QtCore                        	       0x106508aa0 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x106502a64 0x1062e0000 + 2239076
5   QtCore                        	       0x1064fa7b4 0x1062e0000 + 2205620
6   libsystem_pthread.dylib       	       0x18c9c3bc8 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x18c9beb80 thread_start + 8

Thread 12:: QQmlThread
0   libsystem_kernel.dylib        	       0x18c98a498 poll + 8
1   QtCore                        	       0x1064f8d04 qt_safe_poll(pollfd*, unsigned int, QDeadlineTimer) + 76
2   QtCore                        	       0x1064fc9c4 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 904
3   QtCore                        	       0x10637d884 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 596
4   QtCore                        	       0x106465594 QThread::exec() + 332
5   QtCore                        	       0x1064fa7b4 0x1062e0000 + 2205620
6   libsystem_pthread.dylib       	       0x18c9c3bc8 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x18c9beb80 thread_start + 8

Thread 13:: QNetworkAccessManager thread
0   libsystem_kernel.dylib        	       0x18c98a498 poll + 8
1   QtCore                        	       0x1064f8d60 qt_safe_poll(pollfd*, unsigned int, QDeadlineTimer) + 168
2   QtCore                        	       0x1064fc9c4 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 904
3   QtCore                        	       0x10637d884 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 596
4   QtCore                        	       0x106465594 QThread::exec() + 332
5   QtCore                        	       0x1064fa7b4 0x1062e0000 + 2205620
6   libsystem_pthread.dylib       	       0x18c9c3bc8 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x18c9beb80 thread_start + 8

Thread 14:
0   libsystem_pthread.dylib       	       0x18c9beb6c start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib       	       0x18c9beb6c start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	       0x18c9beb6c start_wqthread + 0

Thread 17:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x18c981c34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x18c9943a0 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x18c98a764 mach_msg_overwrite + 484
3   libsystem_kernel.dylib        	       0x18c981fa8 mach_msg + 24
4   CoreFoundation                	       0x18caaec0c __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x18caad528 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x18caac9e8 CFRunLoopRunSpecific + 572
7   AppKit                        	       0x190af178c _NSEventThread + 140
8   libsystem_pthread.dylib       	       0x18c9c3bc8 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18c9beb80 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000600002086730   x2: 0x0000000000000000   x3: 0x000000000000000a
    x4: 0x0000000000000006   x5: 0x000000009901c024   x6: 0x0000600001621810   x7: 0x000000018c97b304
    x8: 0x0000000104d79a84   x9: 0x0000000105015158  x10: 0x0000000104d79ffc  x11: 0x000000000000006b
   x12: 0x0000000000000090  x13: 0x00000000000000ff  x14: 0x00000000001ff800  x15: 0x00000000000007fb
   x16: 0x0000000106d21b38  x17: 0x0000000000000023  x18: 0x0000000000000000  x19: 0x0000600001621810
   x20: 0x00006000009300e0  x21: 0x0000600001621810  x22: 0x0000000000000008  x23: 0x00006000009300f0
   x24: 0x000000016dc34424  x25: 0x0000000000010050  x26: 0x000000010509b481  x27: 0x0000000156feee10
   x28: 0x0000000000000001   fp: 0x000000016dc33f40   lr: 0x0000000104d7a00c
    sp: 0x000000016dc33ec0   pc: 0x0000000104d7a00c cpsr: 0x80001000
   far: 0x0000000000000000  esr: 0x92000006 (Data Abort) byte read Translation fault
```

### Mentions

_No response_

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Bug fix

### Pull request long description:

With these changes mouse interactions with the map work again in my macOS/Qt6 build locally.
Unfortunately, in order to make the code stay reasonably sane, this requires us to bump the minimum Qt version to 5.15 - but then again, anything older than that is simply ridiculous at this point.

### Related issues:

Fixes #4663

### CODE REVIEW

File: packaging/android/qmake-build.sh [hunk 1]
```diff
@@ -117,7 +117,7 @@ if [ -n "${QT5_ANDROID+X}" ] ; then
 elif [ -d "$SUBSURFACE_SOURCE/../${LATEST_QT}" ] ; then
 	export QT5_ANDROID=$SUBSURFACE_SOURCE/../${LATEST_QT}
 else
-	echo "Cannot find Qt 5.12 or newer under $SUBSURFACE_SOURCE/.."
+	echo "Cannot find Qt 5.15 or newer under $SUBSURFACE_SOURCE/.."
```
Comment (mikeller) [inline packaging/android/qmake-build.sh]: **question:** I suspect that this will be overlooked and be outdated as soon as we do the next step up - do we just want to go for something non-specific like 'cannot find a suitable version of Qt...'?

**Review by mikeller — APPROVED** [review]
Apart from the cosmetic remark this looks good, and I've confirmed that zooming and moving the map still works on linux.

**Comment by mikeller** [comment]
But drats, I did the song and dance to try and get the Android version to build with 5.15 a while ago, and I suspect that there is no reasonable / easy solution for this due to version incompatibilities between Qt 5.15 and the Android SDK. 😬

**Comment by dirkhh** [comment]
Isn't Android on 5.15.1???

**Comment by dirkhh** [comment]
AppImage is on something older,  clearly

File: packaging/android/qmake-build.sh (hunk 1 above)
Comment (dirkhh) [reply packaging/android/qmake-build.sh]: There's a variable right there 😁

**Comment by dirkhh** [comment]
I think this is ready to be merged. The effect of the Coverity changes we won't see until merged - but that is broken today, so it can't really be any worse... and with this change we can at least manually trigger things.
The map changes have been reasonably well tested, but as usual we won't really get enough users until this is in a 'latest' build. And the crash fixes for Qt I was able to test both on Linux and macOS.

**Comment by mikeller** [comment]
> Isn't Android on 5.15.1???

Yes, you are right. My fruitless attempts were to update it to 5.15.2.
