### PR TITLE
[BugFix] Fixed midnight datetime bug.

### LINKED ISSUE #4783: [Bug]: UDDF export for dives at 00:00 is non-standard
### Description

If a dive has "no time" associated, so the time is 00:00, when exporting UDDF, the datetime field is incomplete. For example:
`<datetime>2002-06-18T</datetime>` instead of `<datetime>2002-06-18T00:00:00</datetime>`

### Subsurface Version

6.0.5276

### Platform(s)

Windows

### Platform Version

11

### Divecomputer Model

_No response_

### Steps to Reproduce

1. Enter dive with time of 00:00
2. Export UDDF

### Logs

```shell

```

### Mentions

_No response_

### PR DESCRIPTION
**Pull request by mytsvy**
### Describe the pull request:

- [X] Bug fix
- [X] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

When a dive occurs exactly at midnight (00:00:00), XML saving logic was omitting the time attribute. This feature causes some issues for UDDF. This PR ensures that the time attribute is always written.

### Changes made:

1) Omitted the check in `core/save-xml.cpp` file, `show_date()` function. If statement was removed and the row in if block has flattened 1 layer.
2) Tests are ensured that the change is working.

### Related issues:

Fixes #4783 

### Additional information:

Before this fix, a midnight dive would be saved as:
```
<divelog program='subsurface' version='3'>
<settings>
</settings>
<divesites>
</divesites>
<dives>
<dive number='1' otu='3' cns='4%' date='2026-04-20' duration='40:00 min'>
  <cylinder size='11.1 l' workpressure='207.0 bar' description='unknown' depth='66.0 m' />
  <divecomputer model='manually added dive' last-manual-time='40:00 min'>
  <depth max='15.0 m' mean='13.002 m' />
  <sample time='0:00 min' depth='0.0 m' />
  <sample time='1:40 min' depth='15.0 m' />
  <sample time='32:52 min' depth='15.0 m' />
  <sample time='33:59 min' depth='4.95 m' />
  <sample time='39:27 min' depth='4.95 m' />
  <sample time='40:00 min' depth='0.0 m' />
  </divecomputer>
</dive>
</dives>
</divelog>
```
After this fix, it is saved as:
```
<divelog program='subsurface' version='3'>
<settings>
</settings>
<divesites>
</divesites>
<dives>
<dive number='1' otu='3' cns='4%' date='2026-04-21' time='00:00:00' duration='40:00 min'>
  <cylinder size='11.1 l' workpressure='207.0 bar' description='unknown' depth='66.0 m' />
  <divecomputer model='manually added dive' last-manual-time='40:00 min'>
  <depth max='15.0 m' mean='13.002 m' />
  <sample time='0:00 min' depth='0.0 m' />
  <sample time='1:40 min' depth='15.0 m' />
  <sample time='32:52 min' depth='15.0 m' />
  <sample time='33:59 min' depth='4.95 m' />
  <sample time='39:27 min' depth='4.95 m' />
  <sample time='40:00 min' depth='0.0 m' />
  </divecomputer>
</dive>
</dives>
</divelog>
```

When I tried to add a dive manually, the time was like `00:00:06` because of the system clock. I wanted to try editting XML file directly to `00:00:00`. After reopening this save in Subsurface and saving it again, the time attribute disappeared from XML file. With this, I confirmed that the if statement does its own opportunity and this was cause of the bug. After the fix, I did the exact same test case. There was the time attribute. So the fix tech is working.

### CODE REVIEW

File: core/save-xml.cpp [hunk 1]
```diff
@@ -397,9 +397,8 @@ static void show_date(struct membuffer *b, timestamp_t when)
 
 	put_format(b, " date='%04u-%02u-%02u'",
 		   tm.tm_year, tm.tm_mon + 1, tm.tm_mday);
-	if (tm.tm_hour || tm.tm_min || tm.tm_sec)
```
Comment (mikeller) [inline core/save-xml.cpp:400]: **question:** @mturkia you added this check in #564. I am not quite clear why we would not add the time if it is midnight, do you recall why this particular check was added?

Comment (mytsvy) [reply core/save-xml.cpp:400]: I have looked into #564. It seems the intention was being precaution against non-existent values but it omits midnight time too. Removing this check ensures that midnight dives have the time attribute and I didn't observe any side effects. It is necessary for UDDF compatibility.

Comment (mikeller) [reply core/save-xml.cpp:400]: The 'non-existent' part is what gets me - normally I would not consider a time of '00:00:00' as 'non-existent', so I don't see why time whould have been included in #564 - unless this was done in error.
This leaves me wondering if we have special cases where '00:00:00' is actually used to indicate a 'non-existent time', i.e. only the date of a dive is known but not the time.

**Review by mikeller — APPROVED** [review]
